# WhatATheme
markdown: kramdown

# URL of the Site
url: "www.jewsofthediaspora.org"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Google Analytics
google-analytics: UA-163806439-1

# URL for the Image of custom Favicon
favicon-url: assets/images/hamsa-9115778_640.png
# URL of the Image of Cover Hero Image (i.e., the image in the background of the very first section of the Homepage)
leavesimage: ../images/bg-leaves-6975462_1920.png

# Title of the Site
title: Jews of the Diaspora
# Description of the Site
description: Creating and uplifting anti-zionist Jewish ritual events in the Bay Area.
# URL of Image of the Site
site-image: assets/images/meta.jpg
# Keywords of the Site for Google search results
site-keywords: Jews, Jewish, Anti-Zionist, GatherBay, Bay Area, Jewish Ritual, Jewish Events

# About the Site (longer description, mission etc.)
site-about: Jews of the Diaspora intends to cultivate community for ritual-loving anti-zionist Jews, friends and comrades reclaiming their heritage for a better world. Join the newsletter to receive monthly updates on anti-zionist Jewish ritual events happening in the Bay Area, or consider donating to support our mission.

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1hyazinthus@gmail.com

# Name of the Author
author-name: Hyazinth B.
# URL for the Image of the Author
author-image: assets/images/hyazinth-headshot.png
# 60 Words About the Author
author-about: Hyazinth is a ritual organizer and performance artist currently residing in the Bay Area.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://hyazinths.com/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
